name: elections-rmi

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - name: build application
      run: make github-build
    - name: Upload ELECTIONS JARs
      uses: actions/upload-artifact@v2
      with:
        name: ELECTIONS JARs
        path: bin/*.jar
